services:
  app:
    image: golang:1.23
    working_dir: /go/src/app
    volumes:
      - ./app:/go/src/app
    ports:
      - "8080:8080"
    restart: always
    command: >
      sh -c "go run main.go"
